workflows:
  android-workflow:
    name: Android Build
    instance_type: linux
    max_build_duration: 120
    
    environment:
      vars:
        GRADLE_OPTS: "-Xmx3072m -XX:MaxPermSize=512m"
    
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
      
      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          ./gradlew bundleRelease
    
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true