workflows:
  android-workflow:
    name: Android Build
    instance_type: linux
    max_build_duration: 120
    
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g eas-cli
      
      - name: Build Android APK
        script: |
          eas build --platform android --build-type apk --non-interactive
      
      - name: Build Android App Bundle (AAB)
        script: |
          eas build --platform android --build-type app-bundle --non-interactive
    
    artifacts:
      - build-*.apk
      - build-*.aab
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true