workflows:
  android-workflow:
    name: Android Build
    instance_type: linux
    max_build_duration: 120
    
    environment:
      node: 20.19.4
      java: 17
      android_signing:
        - lauritalk_keystore
      vars:
        GRADLE_OPTS: "-Xmx3072m"
    
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      
      - name: Set up signing
        script: |
          cd android
          echo "MYAPP_UPLOAD_STORE_FILE=$CM_KEYSTORE_PATH" >> gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=$CM_KEY_ALIAS" >> gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=$CM_KEYSTORE_PASSWORD" >> gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=$CM_KEY_PASSWORD" >> gradle.properties
      
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
      
      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          ./gradlew bundleRelease
    
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    
    publishing:
      email:
        recipients:
          - lauritalkdev@gmail.com
        notify:
          success: true
          failure: true